org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version_1_21_1=1.21.1
minecraft_version_26_1_2=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version_1_21_1=0.116.17+1.21.1
fabric_api_version_26_1_2=0.155.3+26.1.2
gradle_version=9.5.1
lombok_version=1.18.46
