pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "rain-ui"

include("rain-protocol", "rain-server", "rain-client-core", "rain-fabric-1.21.1", "rain-fabric-26.1.2")

project(":rain-protocol").projectDir = file("java/rain-protocol")
project(":rain-server").projectDir = file("java/rain-server")
project(":rain-client-core").projectDir = file("java/rain-client-core")
project(":rain-fabric-1.21.1").projectDir = file("java/rain-fabric-1.21.1")
project(":rain-fabric-26.1.2").projectDir = file("java/rain-fabric-26.1.2")
