plugins {
    id "net.fabricmc.fabric-loom-remap" version "1.17-SNAPSHOT"
    id "maven-publish"
    id "java"
}

group = "com.rainframework.ui"
version = "1.0.0"

loom {
    splitEnvironmentSourceSets()
    mods {
        "rain-ui" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:0.19.5"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.116.17+1.21.1"

    implementation project(":rain-protocol")
    implementation project(":rain-server")
    implementation project(":rain-client-core")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}

processResources {
    def version = project.version
    inputs.property "version", version
    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
